apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: npminstall
      taskRef:
        name: npm
      params:
        - name: args
          value: ["install"]
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: tests
      runAfter:
        - npminstall
      taskRef:
        name: jasmine
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build
      runAfter:
        - tests
      taskRef:
        name: npm
      params:
        - name: args
          value: ["run", "build"]
      workspaces:
        - name: source
          workspace: shared-workspace
