apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: master
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-source
      taskRef:
        name: clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: npminstall
      runAfter:
        - clone-source
      taskRef:
        name: npm
      params:
        - name: args
          value: ["install"]
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: tests
      runAfter:
        - npminstall
      taskRef:
        name: jasmine
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build
      runAfter:
        - tests
      taskRef:
        name: npm
      params:
        - name: args
          value: ["run", "build"]
      workspaces:
        - name: source
          workspace: shared-workspace
