apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tax-calculator-run-
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: repo-url
      value: https://github.com/BrianGator/juphc-tc_pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tax-calculator-pvc
